version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Counterstrike123
      MYSQL_DATABASE: MR_data
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./backend
    ports:
      - "8000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "mysql+pymysql://root:Counterstrike123@db/MR_data"

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  db_data:
