version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: <YOUR_PASSWORD>
      MYSQL_DATABASE: MR_data #YOUR DATABASE NAME SHOULD BE MR_data
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./backend
    ports:
      - "8000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "<YOUR_DATABASE_URL>/MR_data"

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - api
volumes:
  db_data:
